name: Build and deploy (main)

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [scheduled]

jobs:
  exec:
    uses: ./.github/workflows/build-and-deploy.yml
    secrets: inherit
    with:
      preview: false
