name: Build and deploy (main)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  exec:
    uses: ./.github/workflows/build-and-deploy.yaml
    secrets: inherit
    with:
      preview: false
