name: Build and deploy (PR)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  workflow_dispatch:

jobs:
  exec:
    uses: ./.github/workflows/build-and-deploy.yaml
    secrets: inherit
    with:
      preview: true
